on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crystal-lang/install-crystal@v1
      - run: sudo apt install -y devscripts build-essential lintian
      - run: make release
      - run: mkdir -p build/dorsum-twitch_#{version}-#build_x64
