on:
  push:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - "6379:6379"
        options: --health-cmd "redis-cli ping" --health-interval 5s --health-timeout 5s --health-retries 5        
    steps:
      - uses: actions/checkout@v2
      - uses: crystal-lang/install-crystal@v1
      - run: make lib
      - run: crystal spec
